[Distribution]
Distribution=arch

[Output]
Format=uki
CompressOutput=zstd

[Content]
Bootable=yes
Packages=
        base
        bash
        arch-install-scripts
        btrfs-progs
        cryptsetup
        device-mapper
        dosfstools
        e2fsprogs
        iwd
        lvm2
        mdadm
        networkmanager
        pacman
        pacman-contrib
        python
        snapper
        sudo
        systemd
        systemd-ukify
        util-linux
        xfsprogs
        zstd
[Build]
Incremental=no

[Validation]
SecureBoot=no
